### ISSUE TITLE
are you able to disable to certain page swipe gesture or apply swipe gesture to certain area?

### ISSUE THREAD

**Issue by steve21124** [radianttap/RTWalkthrough#1]

**Comment by radianttap** [comment]
The way this works is each page is inserted into one `UIScrollView`. Thus doing something like this would be down to hacking scroll view's default behavior and enabling/disabling for certain offsets.

**Comment by steve21124** [comment]
Thanks. Yeah, agree. Some of the page has interaction gesture that's why need to disable it for some page
